### ISSUE TITLE
Compatible with istanbul?

### ISSUE THREAD

**Issue by Dashed** [benbria/coffee-coverage#15]
I'm wondering if this is compatible with istanbul?

https://github.com/gotwarlost/istanbul

I'm trying to do something like: `istanbul cover --report html _mocha`

**Comment by silkentrance** [comment]
Here is a sample JSON coverage report we can use for reference

http://gotwarlost.github.io/istanbul/public/coverage/coverage.json

**Comment by jwalton** [comment]
Fixed in 0.5.0.
