### ISSUE TITLE
Travis-CI anyone?

### ISSUE THREAD

**Issue by silkentrance** [benbria/coffee-coverage#30]
I wonder whether you could integrate Travis-CI into your repository?

**Comment by jwalton** [comment]
Now building on codeship, but I'd like to move to travis actually, so leaving this open for now...

**Comment by jwalton** [comment]
Moved to travis-ci.

**Comment by silkentrance** [comment]
@jwalton Great, thanks!

**Comment by jwalton** [comment]
I had to delete the coveralls.io history - seems like coveralls sorts by build number by default, so the travis CI build (#4) was buried at the bottom of all the codeship results.  :P
