### ISSUE TITLE
Shows 0% Coverage

### ISSUE THREAD

**Issue by RaghavendhraK** [benbria/coffee-coverage#35]
Hi,

When I run the mocha, it shows the all the test cases passes. But when I run through the code coverage, it shows as 0% coverage.
This is the command I use.
*"mocha --recursive --compilers coffee:coffee-script/register -r should -r simock -r test/register-handlers.coffee -R html-cov test/unit_test/ > build/coverage.html"*

My register-handlers.coffee looks like this,
```coffeescript
require("coffee-coverage").register(
  {
    path: "relative"
    , basePath: __dirname + '/../src'
    , exclude: ['lib/api/calls/', 'app.coffee']
    , initAll: true
  }
).
```
I am not sure why, but it shows all the codes with line number in the html file. But with 0% coverage and 381 SLOC.

Could you please help me with this.

Thanks,
Raghu

**Comment by WolfgangFellger** [comment]
I have just had the same issue, and tracked it down to the relative path given to basePath. As a workaround, try `path.normalize()` around the argument.

**Comment by RaghavendhraK** [comment]
Yeah, It worked.

Thanks,
Raghu
