### ISSUE TITLE
How can I specify the source directory?

### ISSUE THREAD

**Issue by shamoons** [benbria/coffee-coverage#39]
I am using
```
mocha --require coffee-coverage/register \
       --compilers coffee:coffee-script/register \
       -R html-cov --bail test/ > coverage.html
```

How can I tell it to check all files in the `src` directory for coverage?

**Comment by taoeffect** [comment]
Your tests in `test/` should `require` files from your `src` directory and test them.

**Comment by shamoons** [comment]
So if a `src/` file isn't `require`d, then it won't be covered?

**Comment by taoeffect** [comment]
Correct.

**Comment by jwalton** [comment]
If you use the second option [here](https://github.com/benbria/coffee-coverage#dynamic-compilation) and create your own 'register-handlers.js' file, you can explicitly set the `basePath` and `initAll` parameters to force coffee-coverage to include all files in /src.  See [here](https://github.com/benbria/coffee-coverage/blob/master/src/coffeeCoverage.coffee#L69-L72) for more details.
