### ISSUE TITLE
gulp coffee-coverage mocha istanbul

### ISSUE THREAD

**Issue by WHenderson** [benbria/coffee-coverage#50]
Hi,

I am having trouble using coffee-coverage together with gulp/mocha/istanbul.

It works fine if I run things from the commandline as described in your documentation.

    ./node_modules/.bin/mocha test/test.js
    ./node_modules/.bin/istanbul report

The reports now list that my main target file has 88% coverage and there is a detailed report.

If I try to run it through gulp though

```javascript
// gulp.js
mocha = require('gulp-mocha');
istanbul = require('gulp-istanbul');
...
gulp
.src('test/test.js')
.pipe(mocha())
.pipe(istanbul.writeReports());
```
```javascript
// test/test.js
require('coffee-script/register');
require('coffee-coverage/register-istanbul');
require('./test-coffee.coffee'); // my actual tests
```

It reports 100% code coverage and lists 0 files.
There are also two coverage.json files listed.

    coverage/coverage-coffee.json
    coverage/coverage-final.json

The first one looks to have all the relevant date, the second one is an empty object literal.

The nearest I have been able to figure out is that coffee-coverage cannot find the $$cov.. variable which istanbul uses and so it writes out coverage-coffee, and then istanbul.writeReports ignores it.

Any help is appreciated.

**Comment by jwalton** [comment]
When you run `instanbul report` from the command line, it reads in all the coverage-*.json files and builds a report from all of them.  I'm thinking this is not the case with gulp-istanbul.

coffee-coverage does try to find the existing `$$cov` istanbul variable [here](https://github.com/benbria/coffee-coverage/blob/master/src/instrumentors/Istanbul.coffee#L99).  It looks like gulp-istanbul uses [a little less finesse](https://github.com/SBoudrias/gulp-istanbul/blob/master/index.js#L14) and just generates a `$$cov` variable.  You could explicitly set the coverage variable name:

    istanbul.writeReports({coverageVariable: '$$covMyVar'});

And then you can also explicitly set a `coverageVar` for coffee-coverage by writing your own version of [register-istanbul](https://github.com/benbria/coffee-coverage/blob/master/register-istanbul.js).

**Comment by WHenderson** [comment]
I kinda cheated by simple using gulp-spawn-mocha and a custom setup. It all works pretty much as you've documented now (https://github.com/WHenderson/to-json).

Great library btw. Really appreciate your work.

**Comment by jwalton** [comment]
Glad you got it working. :)
