### ISSUE TITLE
Using with nodeunit?

### ISSUE THREAD

**Issue by lmaccherone** [benbria/coffee-coverage#53]
How would I use coffee-coverage with nodeunit?

**Comment by jwalton** [comment]
I've never used nodeunit, but in theory it shouldn't be too different from anything else.  At some point before you load up any of your code, you want to `require 'coffee-coverage/register-istanbul'`.  This will cause .coffee files to be instrumented by coffee-coverage as they are loaded, and will create `coverage/coverage-coffee.json` when your process terminates.  Then just run your tests.

If that doesn't get you going, if you have a sample project using nodeunit I can play with, I can try to help you out a bit.

**Comment by lmaccherone** [comment]
That was the key to getting it running. I was already running nodeunit programmatically and I was already registering coffee-script, so I just replaced, `require 'coffee-script/register'` with `require 'coffee-coverage/register-istanbul'` and everything worked fine from there. Thanks.
