### ISSUE TITLE
package.json main not found?

### ISSUE THREAD

**Issue by Naxmeify** [benbria/coffee-coverage#58]
Hi if i try to create a custom loader it fails because coffee-coverage cannot be required.

The file (and the whole lib folder) is missing.

**Comment by Naxmeify** [comment]
Ah no problem - had this issue because of #54 wasn't published and i took the master directly. 
Now i found the "prepublish" option.

Thanks a lot!

**Comment by jwalton** [comment]
*whew*  I saw the first comment from this in the notifications on my phone, and you had me going for a minute there.  :)
