### ISSUE TITLE
Remove or rename prepublish hook

### ISSUE THREAD

**Issue by dbartholomae** [benbria/coffee-coverage#75]
Hi there,

currently coffee-coverage uses `prepublish` as script hook. Unfortunately this isn't only run pre publish, as the name suggests, but also after `npm install`. This slows down build processes including coffee-coverage unnecessarily.
It would be great if you could use a different hook or use something like [in-publish](https://github.com/iarna/in-publish) to ensure it doesn't run during `npm install`.

Best,
Daniel

**Comment by jwalton** [comment]
I've read about in-publish before, but I don't get it.  :P  Why is it a problem to run the prepublish hook when you `npm install` from the coffee-coverage project?  It doesn't get run when someone else does an `npm install coffee-coverage`, so it only affects you if you're developing on coffee-coverage, no?

**Comment by dbartholomae** [comment]
Actually I always thought it is also run when `npm install`ing it as a dependency, but you're right :D
