### ISSUE TITLE
.coffee files become excluded if a .js version exists in the same directory

### ISSUE THREAD

**Issue by srgraham** [benbria/coffee-coverage#80]
I have my repo setup so that `potato.coffee` compiles in the same directory to `potato.js`. When potato.js exists, my code coverage always shows 0% for potato.coffee. If I remove potato.js, code coverage for `potato.coffee` goes back to a correct percentage.

example structure where I'm running into issues
```
project
│  README.md
└───lib
│   │   potato.coffee
│   │   potato.js   <- when this exists, coverage of project/lib/potato.coffee is always 0%
│                      when it doesn't exist, coverage of project/lib/potato.coffee is normal
└───test
│    │
│    └───lib
│    │    │   potato.coffee
│    │    │   potato.js
```

Here's my project/test/mocha.opts in case it matters:
```
--compilers coffee:coffee-script/register
--require coffee-coverage/register-istanbul
--reporter spec
--recursive
--growl
test/lib/potato.coffee
```

**Comment by jwalton** [comment]
This isn't really a coffee-coverage problem, it's more of a node.js problem.  If you're using coffee-coverage to dynamically instrument files, then the files get instrumented when node.js loads them, but if you `require "potato"`, then node.js will always try to require potato.js before potato.coffee, and will just ignore the coffee file if the js file is there.  I'm not sure there's anything we can do to fix this.

**Comment by jwalton** [comment]
Closing, since I haven't heard back.
