### ISSUE TITLE
Any way to ignore some directory ?

### ISSUE THREAD

**Issue by luochen1990** [benbria/coffee-coverage#86]
I want the code which is not in the src/ directory not to be counted in the coverage report, is there any way to do that?

**Comment by jwalton** [comment]
Yeah, for sure.  If you register a custom loader, you can set the `exclude` option.  Have a look at https://github.com/benbria/coffee-coverage/blob/master/docs/HOWTO-istanbul.md#writing-a-custom-loader.  (It would be nice if there was an `include`, so you could say "only include /src", but right now there's only an `exclude`.)
