### ISSUE TITLE
Not including all non-coffee JS files in report

### ISSUE THREAD

**Issue by NickLavrov** [benbria/coffee-coverage#89]
I followed the directions for mixed coffee/js projects [here](https://github.com/benbria/coffee-coverage/blob/master/docs/HOWTO-istanbul.md#mixed-js-and-coffee-projects), and it runs fine and includes some js files. But then I added a js file adjacent to a few coffee files, and it doesn't show up in coverage reports.

`./node_modules/.bin/istanbul cover -x 'lib/**' ./node_modules/.bin/_mocha -- --compilers coffee:coffee-script/register --require ./coffee-coverage-loader.js test/lib/**/*.coffee`

Removing the -x tag adds in some but not all JS files.

coffee-coverage-loader.js:
```
var path = require('path');
var coffeeCoverage = require('coffee-coverage');
var projectRoot = path.resolve(__dirname);
var coverageVar = coffeeCoverage.findIstanbulVariable();
// Only write a coverage report if we're not running inside of Istanbul.
var writeOnExit = (coverageVar == null) ? (projectRoot + '/coverage/coverage-coffee.json') : null;

coffeeCoverage.register({
  instrumentor: 'istanbul',
  basePath: projectRoot,
  exclude: ['/test', '/node_modules', '/.git', '/bin', '/coverage', '/dist', '/docs', '/public', '/scripts', '/tasks'],
  coverageVar: coverageVar,
  writeOnExit: writeOnExit,
  initAll: true
});
```
vanilla.js:
```
var test = 8;
var f = function() { return true }
```
If I make a similar coffee file, it IS included.

What's going on? 

![image](https://user-images.githubusercontent.com/13757419/29850770-cbfed64a-8ce4-11e7-9b0c-df719c441c8e.png)

![image](https://user-images.githubusercontent.com/13757419/29850744-9f92d962-8ce4-11e7-863a-230251a31151.png)

**Comment by elidoran** [comment]
The command you show tells it to look for coffee files, `test/lib/**/*.coffee`, where does it tell it to look for JS files?

I have a project looking for both and I have one arg for coffee files and one arg for JS files like `test/lib/coffee/*.coffee test/lib/js/*.js`. It grabs both kinds of files.

**Comment by NickLavrov** [comment]
Thanks @elidoran 

I did not realize I could pass multiple arguments at the time.
