### ISSUE TITLE
Fix JSCoverage HOWTO Documentation

### ISSUE THREAD

**Issue by plroebuck** [benbria/coffee-coverage#92]
See [here](https://github.com/benbria/coffee-coverage/blob/master/docs/HOWTO-jscoverage.md).

Two things:
1. Grammar: Precomiled-sp
1. Shell instructions: the project's binary is `coffeecoverage`, not `coffeeCoverage`.

Would be nice if snippets were in language-coded blocks (e.g., ```coffeescript). 
Personally prefer shell-instructions to include prompt ('$ ').

**Comment by jwalton** [comment]
Updated.  Have a quick read through and make sure I didn't miss anything?  Thanks!

**Comment by plroebuck** [comment]
Few more:
1. Contents still has misspelling. Anchor link to section no longer works.
1. Section header still misspelled (Precomiled)
1. Code blocks for 'Quick Start' and 'Precompiled Source' sections (```sh)
1. Code block for `package.json` in 'Run with NPM' section (```json)

**Comment by jwalton** [comment]
Fixed.  Thanks again!
